/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Body handle for streaming large request bodies
 * Used when the body is too large to buffer in memory
 */
export declare class BodyHandle {
  /**
   * Read the next chunk of the body
   * Returns null when the body is fully consumed
   * Note: This is marked unsafe because it takes &mut self in async context
   */
  read(): Promise<Buffer | null>;
  /** Check if there's more data to read */
  isClosed(): boolean;
}

/**
 * Request context passed from Rust to JavaScript handler
 * Contains all request information and a callback to send the response
 */
export declare class RequestContext {
  /** Get the HTTP method */
  get method(): string;
  /** Get the full URL */
  get url(): string;
  /** Get headers as an array of {name, value} objects */
  get headers(): Array<HeaderPair>;
  /** Get the request body as a Buffer (or null if no body) */
  get body(): Buffer | null;
  /** Get the client IP address */
  get clientAddress(): string;
  /**
   * Send a response back to the client
   * This must be called exactly once per request
   */
  respond(response: JsResponse): void;
}

/** High-performance HTTP server with Fetch Event API */
export declare class Server {
  /** Create a new server with the given options */
  constructor(options: ServerOptions);
  /**
   * Set the fetch event handler
   * This should be called before listen()
   */
  setHandler(handler: (err: Error | null, arg: RequestContext) => void): void;
  /** Start the server and begin accepting connections */
  listen(): Promise<void>;
  /** Gracefully shutdown the server */
  close(): Promise<void>;
  /** Get current server statistics */
  stats(): ServerStats;
}

/** Header as a two-element array [name, value] for JavaScript */
export interface HeaderPair {
  name: string;
  value: string;
}

/** Header key-value pair for use in JsResponse */
export interface JsHeader {
  name: string;
  value: string;
}

/**
 * Response object passed from JavaScript to Rust
 * Contains the HTTP response data to send back to the client
 */
export interface JsResponse {
  /** HTTP status code (200, 404, 500, etc.) */
  status: number;
  /** Response headers as key-value pairs */
  headers: Array<JsHeader>;
  /** Response body (None for empty body) */
  body?: Buffer;
}

/** Server options passed from JavaScript */
export interface ServerOptions {
  /** Port to listen on */
  port: number;
  /** Host to bind to (default: "0.0.0.0") */
  host?: string;
  /** Enable SO_REUSEPORT for multi-core scaling */
  reusePort?: boolean;
  /** Maximum concurrent connections (default: 65536) */
  maxConnections?: number;
  /** Request body size limit in bytes (default: 10MB) */
  maxBodySize?: number;
  /** Request timeout in milliseconds (default: 30000) */
  timeout?: number;
}

/** Server statistics */
export interface ServerStats {
  /** Number of active connections */
  activeConnections: number;
  /** Total requests handled (as f64 to avoid napi u64 issues) */
  totalRequests: number;
  /** Requests per second (rolling average) */
  requestsPerSecond: number;
  /** Average latency in milliseconds */
  avgLatencyMs: number;
}
